version: '3.9'

services:
  bytebank:
    build: ../app-with-zones/full-site
    image: bytebank:latest
    container_name: bytebank
    environment:
      NEXT_PUBLIC_INVESTMENTS_BASE_URL: http://localhost:3001
    networks:
      - bytebank-network
    ports:
      - '3000:3000'
    depends_on:
      - bytebank-investments
      - bytebank-api

  bytebank-investments:
    build: ../app-with-zones/investments
    image: bytebank-investments:latest
    container_name: bytebank-investments
    networks:
      - bytebank-network
    ports:
      - '3001:3000'
    depends_on:
      - bytebank-api

  bytebank-api:
    build: ../app-with-zones/api
    image: bytebank-api:latest
    container_name: bytebank-api
    networks:
      - bytebank-network
    ports:
      - '3002:3000'

networks:
  bytebank-network:
    driver: bridge
