### Create user
POST http://ec2-18-188-52-88.us-east-2.compute.amazonaws.com:3000/user
Content-Type: application/json

{
  "username": "Aluno Carequinha",
  "email": "teste@gmail.com",
  "password": "testes"
}
ps aux | grep node

### get account
GET http://ec2-18-188-52-88.us-east-2.compute.amazonaws.com:3000/account
Content-Type: application/json
